name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@main
      - name: Create .env
        run: echo 'PORT=${{ secret.PORT }}' > .env
      
      - name: Run build
        run: docker-composer up -d
